export { CodeEditor } from './components/CodeEditor'
export { useEditor } from './hooks/useEditor'
export { useTestRunner } from './hooks/useTestRunner'
export { codeAnalyzer } from './services/code-analyzer'
export { testService } from './services/test-service'
export type { CodeAnalysisResult, TestResult } from './types/service'
export { astTester } from './utils/ast-tester'
