export { default as CodeEditor } from './components/CodeEditor'
export { useEditor } from './hooks/useEditor'
export { useTestRunner } from './hooks/useTestRunner'
export { codeAnalyzerService } from './services/code-analyzer'
export { testService } from './services/test-service'
export type { CodeAnalyzerAPI, ASTContext, Result, ServiceError, CodeAnalysisResult } from './types/service'
export { testWithAST, testWithPattern, runTestCase, runAllTests } from './utils/ast-tester'
